#!/bin/sh

# this file was taken from systemd-204-14~bpo70+1 (systemd-logind-launch)

# Copyright: 2010-2013 Tollef Fog Heen <tfheen@debian.org>
#            2013 Michael Biebl <biebl@debian.org>
#            2013 Michael Stapelberg <stapelberg@debian.org>
# License: LGPL-2.1+

if ! mountpoint -q /sys/fs/cgroup; then
    mount -t tmpfs -o uid=0,gid=0,mode=0755,size=1024 none /sys/fs/cgroup
fi
if ! mountpoint -q /sys/fs/cgroup/systemd; then
    mkdir -p /sys/fs/cgroup/systemd
    mount -t cgroup -o nosuid,noexec,nodev,none,name=systemd systemd /sys/fs/cgroup/systemd
fi
mkdir -p /run/systemd

# necessary for unprivileged LXC containers
ulimit -S -n 16384 || true
ulimit -H -n 16384 || true

exec logoutd
